### ISSUE TITLE
create the IRB consent page

### ISSUE THREAD

**Issue by jtsmn** [crowd-lab/distributed_social_translucence#30]
This task means creating the page in which we debrief workers and ask them to consent. It needs to occur _after_ someone has completed the moderation phase. Consent doc we sent to IRB is at: https://drive.google.com/open?id=1g25mk15q616fiUcKQsScXHVBQbp67IXE

Deliverables will include a demo of the functioning page.

**Comment by christopherhurt** [comment]
Should be part of "done" page.

**Comment by christopherhurt** [comment]
Record consent in database, selected by button on done page.

**Comment by jtsmn** [comment]
The text on the page needs to be updated
